/* Do not edit this file. It was automatically generated. */

#ifndef HEADER_FreqMeter
#define HEADER_FreqMeter
/*
htop - TemperatureMeter.h
(C) 2013 Ralf Stemmer
(C) 2014 Blair Bonnett
Released under the GNU GPL, see the COPYING file
in the source distribution for its full text.
*/

#include "Meter.h"

extern int FreqMeter_attributes[];

extern MeterClass FreqMeter_class;

#endif
